### ISSUE TITLE
Creating a zone that is accesible only for mfa logged in users.

### ISSUE THREAD

**Issue by navid-dada** [pondersource/nextcloud-mfa-awareness#25]
we can check [this app](https://apps.nextcloud.com/apps/files_accesscontrol) and find out mechanisms of applying access control on  folders by defining some criteria. and after that, we can create similar criteria for MFA access control.

**Comment by nickvergessen** [comment]
Sounds like a nice idea. For that it should provide a check for the workflow engine:
https://github.com/nextcloud/server/tree/master/apps/workflowengine/lib/Check

But at the moment those checks can not be provided by apps I think.

**Comment by michielbdejong** [comment]
In our session today we found that we were able to edit https://github.com/nextcloud/server/blob/master/apps/workflowengine/lib/Check/FileMimeType.php so that it bars access based on the mfa-verified flag from the session, instead of based on the actual file mime type.

Steps left:
* [ ] #26
* [ ] #27

**Comment by michielbdejong** [comment]
Done (but see list of loose ends in [milestone 4](https://github.com/pondersource/nextcloud-mfa-awareness/milestone/4)

**Comment by michielbdejong** [comment]
Issue #27 was moved to [milestone 4](https://github.com/pondersource/nextcloud-mfa-awareness/milestone/5)
