### ISSUE TITLE
Implement gss attribute forwarding

### ISSUE THREAD

**Issue by mickenordin** [pondersource/nextcloud-mfa-awareness#3]
I simply took out the dependency on phpunit (as mentioned in #2  and built it. It seems this code wants to use code from user_saml, which is not enabled on our nodes, it is only enabled on the global site selector, so maybe we need to pass the mfa attribute from user saml via gss? If user_saml app is disabled we get this error in the log.
```
node1:~# grep bFmGgSJfXSv9HRvgzcgU /opt/nextcloud/nextcloud.log
{"reqId":"bFmGgSJfXSv9HRvgzcgU","level":0,"time":"2022-09-02T09:15:16+00:00","remoteAddr":"94.234.100.240","user":"kano@sunet.se","app":"globalsiteselector","method":"GET","url":"/index.php/apps/mfachecker/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0","version":"23.0.8.2"}
{"reqId":"bFmGgSJfXSv9HRvgzcgU","level":3,"time":"2022-09-02T09:15:16+00:00",
"remoteAddr":"94.234.100.240","user":"kano@sunet.se","app":"index","method":"GET","url":"/index.php/apps/mfachecker/","message":"Could not resolve userData! Class \"userData\" does not exist","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0","version":"23.0.8.2","exception":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve userData! Class \"userData\" does not exist","Code":0,"Trace":[{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map"},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":463,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":435,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":144,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","Line":100,"Previous":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve OCA\\User_SAML\\UserData! Class \"OCA\\User_SAML\\UserData\" does not exist","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/lib/private/ServerContainer.php","line":161,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":438,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map"},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":463,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":435,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":144,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","Line":120},"CustomMessage":"--"}}
```

If I enable the user_saml app, it will display "User Is Logged in directly", so I think maybe we also need to patch the global site selector app to pass this info on...

**Comment by michielbdejong** [comment]
Indeed, the mfachecker app from this repo [tries to obtain](https://github.com/pondersource/nextcloud-mfa-awareness/blob/bc3bba3/mfachecker/lib/Controller/PageController.php#L5) a singleton instance of `OCA\User_SAML\UserData`, and this will only exist if the [user_saml](https://github.com/nextcloud/user_saml) app is installed on the same server.

> If I enable the user_saml app, it will display "User Is Logged in directly"

I think you're right, because even though you enable the app on the gss slave, that just means that the code is loaded into scope (making the error message go away). It will not have been used for the login.

> maybe we need to pass the mfa attribute from user saml via gss?
[...]
> I think maybe we also need to patch the global site selector app to pass this info on...

As discussed in our last meeting, yes, that seems like the way forward.

Did you talk to the Nextcloud developers about this? Can they provide a version of gss that passes this attribute on?

In any case, we should probably:
* remove the hard dependency on user_saml and make it optional
* add an optional dependency on gss slave to read attributes from there if available

**Comment by michielbdejong** [comment]
Leaving this issue open to track our dependency on gss attribute passing.

**Comment by mickenordin** [comment]
> Did you talk to the Nextcloud developers about this? Can they provide a version of gss that passes this attribute on?

Yes, I did talk to Nextcloud about this,  Navid should  have a support account with Nextcloud now if I am correctly informed, and the ticket tracking this is: https://support.nextcloud.com/#ticket/zoom/36210 

> In any case, we should probably:
> 
>     * remove the hard dependency on user_saml and make it optional
> 
>     * add an optional dependency on gss slave to read attributes from there if available

Agreed!

**Comment by michielbdejong** [comment]
>  Navid should have a support account with Nextcloud now if I am correctly informed

Ah, he hadn't received a signup email, but he was able to get access to the support ticket using password reset + his email address. Great! That will help a lot.

**Comment by michielbdejong** [comment]
As discussed in today's meeting, we'll fork the globalsiteselector to implement this.
Passing the attribute from the SAML user data into the JWT at the GSS leader, and then reading it out at the GSS follower.

**Comment by michielbdejong** [comment]
* [ ] in the GSS leader, put the data into the JWT
* [ ] in the GSS follower, read it out of the JWT and make it available
* [ ] in mfachecker read the data that is made available by the GSS app and display it

**Comment by mrvahedi68** [comment]
Here we can add any data to options and will encrypt in JWT.

https://github.com/nextcloud/globalsiteselector/blob/03b191361014fad6b5c580376935ebdb35990270/lib/Master.php#L174

**Comment by michielbdejong** [comment]
I forked the repo from nextcloud and created an 'attribute-forwarding' branch in our clone for this:
https://github.com/pondersource/globalsiteselector/branches

**Comment by navid-dada** [comment]
I found this line of code in the master code:
https://github.com/nextcloud/globalsiteselector/blob/03b191361014fad6b5c580376935ebdb35990270/lib/Master.php#L135

as the comment says they are excluding raw data from options and only send the formatted data to the follower side.
so we have two options:
- just comment the line no 137
- Find a way to add metadata such as location mfa_verified to formatted data in ssp by configuring it (not changing the code)

so the second one is the best way because there is no more need to add merge requests on GSS and also all needed properties will be transferred transparently and dynamically.

**Comment by mrvahedi68** [comment]
We can add something like that into `user_saml` :

File: https://github.com/nextcloud/user_saml/blob/3884edd12e29987ccaac9eb7facbcf16cc892939/lib/UserBackend.php#L476

Code:

`

    try {

			$result['formatted']['custom_field'] = $this->getAttributeArrayValue('saml-attribute-mapping-custom_field_mapping', $attributes);

		} catch (\InvalidArgumentException $e) {

			$result['formatted']['custom_field'] = null;

		}
`

**Comment by navid-dada** [comment]
I added this line of code and it will add a new test input inside the admin panel of user_saml.
https://github.com/pondersource/user_saml/blob/b8af1283a5aa2dd622f1c65122fb0f8c17951892/lib/SAMLSettings.php#L68

**Comment by michielbdejong** [comment]
We found two pieces of existing work in this context:

* an old one, merged: https://github.com/nextcloud/globalsiteselector/commit/e042b9dd9631d43f3d83fcb488fd5bd207c0019b
* a recent one, in draft (maybe this was in response to SUNET's feature request for this?): https://github.com/nextcloud/globalsiteselector/pull/75


As discussed in today's standup, the approach will be to:
1) submit a PR to `user_saml` that:
* allows the admin to specify a column name to map to 'MFA status'
* if set, includes that value in the return value of `getUserData()`
2) submit a PR to `globalsiteselector` that sets the value into the session, in the same way that [this is done for `globalScale.uid`].(https://github.com/nextcloud/globalsiteselector/blob/03b191361014fad6b5c580376935ebdb35990270/lib/Controller/SlaveController.php#L158)

This is the clean way to do it, because the GSS master already calls `getUserData` on the `user_saml` backend.
An alternative way would be to leave the `user_saml` code untouched and read out the SAML user data from the session, in the same way that we already did that for the setup where the user logs in locally with SAML. We'll just make both work, and then you can choose. :)

**Comment by navid-dada** [comment]
this issue finished with bellow comment:
 https://github.com/pondersource/nextcloud-mfa-awareness/commit/dcf3619d2e42ee2ee43583c3b5be6c810c38724e
