### ISSUE TITLE
User flow for setting/unsetting 'MFA required' tag

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#35]
Maybe we can use the existing tag-setting/unsetting GUI for this, then we don't have to do anything for this.

**Comment by mrvahedi68** [comment]
We are creating one new app for Nextcloud to do two things:

- [ ] Add another tab to file and folder details that inside it user can set/unset check for enabling or disabling Mfa verified zone. (User must be admin or owner of the file)
- [ ] Add a new section inside the security section of the administration panel so that the Admin can select the specified tag to be used for creating the Mfa zone in the background.

[Here](https://github.com/pondersource/mfaverifiedzone) is the repository for the new app, and [This](https://github.com/pondersource/mfaverifiedzone/pull/1) is a pull request that shows the development progress.

**Comment by michielbdejong** [comment]
@mrvahedi68 what is the status of this issue?

**Comment by mrvahedi68** [comment]
Done with this PR:
https://github.com/pondersource/mfaverifiedzone/pull/1
